import type { Metadata } from "next";
import "./globals.css";
import { MantineProvider } from "@mantine/core";
import "@mantine/core/styles.css";
import '@mantine/charts/styles.css';
import Providers from "@/components/Providers/Providers";
// import '@mantine/dropzone/styles.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="
        "
      >
        <Providers>
          <MantineProvider
            theme={{
              headings: {
                fontFamily: "Instrument Sans, sans-serif",
              },
            }}
          >
            {children}
          </MantineProvider>
        </Providers>
      </body>
    </html>
  );
}
